/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adproc;

/**
 *
 * @author Fred
 */
public class OrderForm extends javax.swing.JFrame {

    /**
     * Creates new form OrderForm
     */
    public OrderForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboColour1 = new javax.swing.JComboBox();
        comboColour2 = new javax.swing.JComboBox();
        textfLength = new javax.swing.JTextField();
        textfOuterDiameter = new javax.swing.JTextField();
        comboPlasticGrade = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        textbQuantity = new javax.swing.JTextField();
        checkInsulation = new javax.swing.JCheckBox();
        checkReinforcement = new javax.swing.JCheckBox();
        checkChemicalResistance = new javax.swing.JCheckBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jSeparator15 = new javax.swing.JSeparator();
        jSeparator16 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PipesR'us");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Pipes R Us");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, -1, -1));

        jLabel2.setText("Length");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel3.setText("Outer Diameter");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));

        jLabel4.setText("Plastic Grade");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel6.setText("Colour 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 22));

        jLabel7.setText("Colour 2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel8.setText("Insulation");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 70, -1));

        jLabel9.setText("Reinforcement");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 100, -1));

        jLabel10.setText("Chemical Resistance");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 271, -1, -1));

        jLabel11.setText("Quantity");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        jButton1.setText("Add to Cart");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 140, 50));

        comboColour1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "red", "green", "blue" }));
        comboColour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColour1ActionPerformed(evt);
            }
        });
        getContentPane().add(comboColour1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        comboColour2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "blue", "Item 2", "Item 3", "Item 4" }));
        comboColour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColour2ActionPerformed(evt);
            }
        });
        getContentPane().add(comboColour2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        textfLength.setText("Length (m)");
        textfLength.setBorder(null);
        textfLength.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        textfLength.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textfLengthFocusGained(evt);
            }
        });
        textfLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfLengthActionPerformed(evt);
            }
        });
        getContentPane().add(textfLength, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 160, -1));

        textfOuterDiameter.setText("Outer Diameter (inches) ");
        textfOuterDiameter.setBorder(null);
        textfOuterDiameter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textfOuterDiameterActionPerformed(evt);
            }
        });
        getContentPane().add(textfOuterDiameter, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 180, -1));

        comboPlasticGrade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboPlasticGrade.setAlignmentX(0.0F);
        getContentPane().add(comboPlasticGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 90, 20));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("* Select Pipe Length (meters) [max 6m] \n* Select Outer Diameter (inches)\n* Select Plastic Grade\n* Select Colour(s) or leave blank if Colour is undesired\n* Select Insulation/Reinforcement\n* Select Chemical Resistance\n* Select Quantity\n* Add to Cart \n* Repeat until satisfied then submit to be taken to Payment");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(539, 0, 460, 160));

        textbQuantity.setText("Enter Quantity");
        textbQuantity.setBorder(null);
        getContentPane().add(textbQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, -1, -1));

        checkInsulation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInsulationActionPerformed(evt);
            }
        });
        getContentPane().add(checkInsulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 30, -1));
        getContentPane().add(checkReinforcement, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));
        getContentPane().add(checkChemicalResistance, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, 20));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 630, 270));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 90, 330, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 60, 332, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 38, 20, 300));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 130, 332, 10));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, 332, -1));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));
        getContentPane().add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 230, 332, -1));
        getContentPane().add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 260, 332, -1));
        getContentPane().add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 290, 332, -1));
        getContentPane().add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 320, 332, 10));

        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 34, 10, 290));

        jButton2.setText("Go to Payment");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 450, 140, 50));

        jSeparator15.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, -1, 290));
        getContentPane().add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 30, 332, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void textfOuterDiameterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfOuterDiameterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfOuterDiameterActionPerformed

    private void textfLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textfLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textfLengthActionPerformed

    private void textfLengthFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textfLengthFocusGained
            // TODO add your handling code here:
        
    }//GEN-LAST:event_textfLengthFocusGained

    private void comboColour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboColour1ActionPerformed

    private void checkInsulationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInsulationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkInsulationActionPerformed

    private void comboColour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColour2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboColour2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkChemicalResistance;
    private javax.swing.JCheckBox checkInsulation;
    private javax.swing.JCheckBox checkReinforcement;
    private javax.swing.JComboBox comboColour1;
    private javax.swing.JComboBox comboColour2;
    private javax.swing.JComboBox comboPlasticGrade;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField textbQuantity;
    private javax.swing.JTextField textfLength;
    private javax.swing.JTextField textfOuterDiameter;
    // End of variables declaration//GEN-END:variables
}
